# Disable automatic runs of this pipeline when changes are pushed to the repository.
trigger: none

# Disable automatic runs of this pipeline when a PR is create.
pr: none

# Add the pipeline that builds the packages as a resource.
# This allows the deployment pipeline to be triggered whenever
# the build pipeline completes.
resources:
  pipelines:
  - pipeline: build-pipeline   # The name for the triggering build pipeline within this script
    source: device-detection-node-create-packages # Name of the pipeline from here: https://51degrees.visualstudio.com/Pipeline/_build
    trigger: true 
  repositories:
  - repository: ciTemplates # Id of the repository used to reference to in this script
    type: git
    name: common-ci # Name of the actual repository

# Include shared variables
variables:
- template: shared-variables.yml@ciTemplates
- name: targetBranch
  value: 'refs/heads/master'
- group: CIAutomation

stages:       
              
- stage: publish_npm
  displayName: Publish to NPM
  condition: eq(variables['build.sourceBranch'], variables['targetBranch'])
  jobs:
  - deployment: deploy_npm
    displayName: Deploy to NPM
    pool:
      vmImage: $(linuxImage)
      workspace:
        clean: all
    environment: npm
    strategy:
      runOnce:
        deploy:
          steps: 
          
          - template: node/shared-extract-and-publish-packages.yml@ciTemplates
            parameters:
              publishConnection: 'NPM publish connection'
              packageName: 'fiftyone.devicedetection'
              internalFeedId: $(InternalFeedId)
              
          - template: node/shared-extract-and-publish-packages.yml@ciTemplates
            parameters:
              publishConnection: 'NPM publish connection'
              packageName: 'fiftyone.devicedetection.cloud'
              internalFeedId: $(InternalFeedId)
              
          - template: node/shared-extract-and-publish-packages.yml@ciTemplates
            parameters:
              publishConnection: 'NPM publish connection'
              packageName: 'fiftyone.devicedetection.onpremise'
              internalFeedId: $(InternalFeedId)
              
          - template: node/shared-extract-and-publish-packages.yml@ciTemplates
            parameters:
              publishConnection: 'NPM publish connection'
              packageName: 'fiftyone.devicedetection.shared'
              internalFeedId: $(InternalFeedId)


- template: shared-publish-github-stage.yml@ciTemplates
  parameters:
    imageName: $(linuxImage)
    branchName: ${{ variables.targetBranch }}