parameters:
- name: publishBinaries
  type: boolean
  default: false
- name: windowsImage
- name: linuxImage
- name: macImage
- name: runTests
  type: string
  default: 'On'

stages:
- stage: Data

  jobs:
  - job: Download_Data_Files
    condition: ne(${{ parameters.runTests }}, 'Off')

    variables: 
      - group: PackageFeedAccessToken
      - group: InternalKeys

    pool:
      vmImage: ${{ parameters.linuxImage }}

    steps:

    - task: Bash@3
      displayName: 'Download TAC V4 Hash data file'
      inputs:
        targetType: 'inline'
        script: 'wget "https://distributor.51degrees.com/api/v2/download?LicenseKeys=$(DeviceDetectionLicenseKey)&Type=27&Download=True&Product=23" -O "51Degrees.hash.gz"'
    
    - task: Bash@3
      displayName: 'Download TAC V4 CSV data file'
      inputs:
        targetType: 'inline'
        script: 'wget "https://distributor.51degrees.com/api/v2/download?LicenseKeys=$(DeviceDetectionLicenseKey)&Type=21&Download=True&Product=23" -O "$(Build.SourcesDirectory)/51Degrees-Tac.zip"'
    
    - task: ExtractFiles@1
      displayName: 'Extract TAC V4 Hash data file'
      inputs:
        archiveFilePatterns: '**/*.hash.gz'
        destinationFolder: '$(Build.ArtifactStagingDirectory)'
        cleanDestinationFolder: false
        overwriteExistingFiles: true
    
    - task: Bash@3
      displayName: 'Extract TAC V4 CSV data file'
      inputs:
        targetType: 'inline'
        script: 'unzip -p $(Build.SourcesDirectory)/51Degrees-Tac.zip 51Degrees-Tac-All.csv > $(Build.ArtifactStagingDirectory)/51Degrees.csv'
        workingDirectory: '$(Build.SourcesDirectory)'
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'dataFiles'
        publishLocation: 'Container'

- template: shared-build-and-test-stage.yml
  parameters:
    stageName: Windows
    imageName: ${{ parameters.windowsImage }}
    osName: 'win32'
    stageDependency: 'Data'
    publishBinaries: ${{ parameters.publishBinaries }}
    runTests: ${{ parameters.runTests }}

- template: shared-build-and-test-stage.yml
  parameters:
    stageName: Linux
    imageName: ${{ parameters.linuxImage }}
    osName: 'linux'
    stageDependency: 'Data'
    publishBinaries: ${{ parameters.publishBinaries }}
    runTests: ${{ parameters.runTests }}

- template: shared-build-and-test-stage.yml
  parameters:
    stageName: MacOS
    imageName: ${{ parameters.macImage }}
    osName: 'darwin'
    stageDependency: 'Data'
    publishBinaries: ${{ parameters.publishBinaries }}
    runTests: ${{ parameters.runTests }}

