name: Nightly PRs to Main

on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: false
        type: boolean
        description: Dry Run
  schedule:
    - cron: '0 1 * * *'

jobs:
  Nightly_PRs_to_Main:
    uses: 51Degrees/common-ci/.github/workflows/nightly-prs-to-main.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      cache-assets: true
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      asset-keys: '{"DeviceDetection": "${{ secrets.DEVICE_DETECTION_KEY }}", "DeviceDetectionUrl": "${{ secrets.DEVICE_DETECTION_URL }}", "CsvUrl": "${{ secrets.CSV_URL }}", "TestResourceKey": "${{ secrets.SUPER_RESOURCE_KEY}}", "TestSuperResourceKey": "${{ secrets.SUPER_RESOURCE_KEY }}", "TestPlatformResourceKey": "${{ secrets.ACCEPTCH_PLATFORM_KEY }}", "TestHardwareResourceKey": "${{ secrets.ACCEPTCH_HARDWARE_KEY }}", "TestBrowserResourceKey": "${{ secrets.ACCEPTCH_BROWSER_KEY }}", "TestNoSetHeaderResourceKey": "${{ secrets.ACCEPTCH_NONE_KEY }}", "TestLicenseKey": "${{ secrets.DEVICE_DETECTION_KEY }}"}'
