name: Nightly Publish Main

on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: 'false'
        description: Dry Run
  schedule:
    - cron: '0 1 * * *'

jobs:
  Nightly_Publish_Main:
    uses: 51Degrees/common-ci/.github/workflows/nightly-publish-main.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun }}
      build-platform: ubuntu-latest
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      asset-keys: '{"DeviceDetection": "${{ secrets.DEVICE_DETECTION_KEY }}", "DeviceDetectionUrl": "${{ secrets.DEVICE_DETECTION_URL }}", "TestResourceKey": "${{ secrets.SUPER_RESOURCE_KEY}}", "NPMAuthToken": "${{ secrets.NPM_AUTH_TOKEN}}", "UsePublishTests": true}'
